### ISSUE TITLE
Notion doesn't include the correct <title> anymore

### ISSUE THREAD

**Issue by snario** [shariq/shar.iq#1]
The title is always `<title>Notion – Docs, Wikis, Tasks. Seamlessly in one.</title>` as far as I can tell. Example if you open in Incognito: https://www.notion.so/Shariq-s-Scrapbook-d065149ff38a4e7a9b908aeb262b0f4f

Might fix sometime this week

**Comment by shariq** [comment]
Sorry, just seeing these issues now. Reported this to Simon and he fixed it :)
